services:
  - type: web
    name: agm-pro
    env: static
    buildCommand: corepack enable && corepack pnpm install --frozen-lockfile && corepack pnpm build:render
    staticPublishPath: ./src/frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
